//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSRSComSim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSRSComSim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,Adamant arrow,Free-to-play,0,0,0,0,0,0,0,0,0,0,0,0,31,0,0,0
        ///Equipment,Adamant bolts,Members,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0
        ///Equipment,Adamant brutal,Members,0,0,0,0,0,0,0,0,0,0,0,0,45,0,0,0
        ///Equipment,Adamant javelin,Members,0,0,0,0,0,0,0,0,0,0,0,0,107,0,0,0
        ///Equipment,Amethyst arrow,Members,0,0,0,0,0,0,0,0,0,0,0,0,55,0,0,0
        ///Equipment,Amethy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,3rd age druidic robe top,Members,1.5,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0
        ///Equipment,3rd age platebody,Members,9.979,0,0,0,-20,0,96,108,113,-4,97,0,0,0,0,0
        ///Equipment,3rd age range top,Members,4,0,0,0,-15,30,55,47,60,60,55,0,0,0,0,0
        ///Equipment,3rd age robe top,Members,2.7,0,0,0,24,0,0,0,0,24,0,0,0,0,0,0
        ///Equipment,Adamant chainbody,Free-to-play,7.711,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,3rd age cloak,Members,0.005,0,0,0,0,0,9,9,9,9,9,0,0,0,5,0
        ///Equipment,3rd age druidic cloak,Members,0.4,0,0,0,1,0,3,3,3,3,3,0,0,0,3,0
        ///Equipment,Accumulator max cape,Members,0.453,0,0,0,0,4,0,1,0,4,0,0,0,0,0,0
        ///Equipment,Achievement diary (t),Members,0.453,0,0,0,0,0,9,9,9,9,9,0,0,0,4,0
        ///Equipment,Achievement diary cape ,Members,0.453,0,0,0,0,0,9, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cape {
            get {
                return ResourceManager.GetString("Cape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,Adamant boots,Members,1.36,0,0,0,-3,-1,10,11,12,0,0,1,0,0,0,0
        ///Equipment,Ancient d&apos;hide boots,Members,1.4,0,0,0,-10,7,4,4,4,4,4,0,0,0,1,0
        ///Equipment,Angler boots,Members,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,Ankou socks,Members,0.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,Antisanta boots,Free-to-play,0.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,HPHeals
        ///Food,Shrimp,Free-to-play,0.1,3
        ///Food,Cooked chicken,Free-to-play,0.1,3
        ///Food,Cooked meat,Free-to-play,0.1,3
        ///Food,Sardine,Free-to-play,0.1,4
        ///Food,Bread,Free-to-play,0.1,5
        ///Food,Herring,Free-to-play,0.1,5
        ///Food,Mackerel,Member,0.1,6
        ///Food,Choc-ice,Member,0.1,6
        ///Food,Trout,Free-to-play,0.1,7
        ///Food,Cod,Member,0.1,7
        ///Food,Pike,Free-to-play,0.1,8
        ///Food,Roast beast meat,Member,0.1,8
        ///Food,Pineapple punch,Member,0.1,9
        ///Food,Salmon,Free-to-play,0.1,9
        ///Food,Tuna,Free-to-play,0.1,10        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,3rd age vambraces,Members,1,0,0,0,-10,11,6,5,7,9,0,0,0,0,0,0
        ///Equipment,Abyssal bracelet,Members,0.25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,Adamant gloves,Members,0.226,7,7,7,4,7,7,7,7,4,7,7,0,0,0,0
        ///Equipment,Ancient bracers,Members,1,0,0,0,-10,11,6,5,7,8,0,0,0,0,1,0
        ///Equipment,Ankou gloves,Members,0.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipmen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,3rd age full helmet,Members,0.907,0,0,0,-5,-2,47,49,43,-3,48,0,0,0,0,0
        ///Equipment,3rd age mage hat,Members,0.4,0,0,0,8,0,0,0,0,8,0,0,0,0,0,0
        ///Equipment,3rd age range coif,Members,1,0,0,0,-2,9,4,7,10,5,8,0,0,0,0,0
        ///Equipment,4th birthday hat,Free-to-play,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,A powdered wig,Members,0.4,0,0,0,0,0,0,0,0,0,0,0,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,3rd age druidic robe bottoms,Members,1.5,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0
        ///Equipment,3rd age platelegs,Members,2.721,0,0,0,-25,-2,78,76,83,-5,75,0,0,0,0,0
        ///Equipment,3rd age plateskirt,Members,2.721,0,0,0,-25,-2,78,76,83,-5,75,0,0,0,0,0
        ///Equipment,3rd age range legs,Members,3,0,0,0,-10,17,31,25,33,30,31,0,0,0,0,0
        ///Equipment,3rd age robe,Members,1.8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,&apos;perfect&apos; necklace,Members,0.01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,10th squad sigil,Members,0.085,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,3rd age amulet,Members,0.003,0,0,0,15,0,0,0,0,10,0,0,0,0,0,0
        ///Equipment,Amulet of accuracy,Free-to-play,0.01,4,4,4,4,4,0,0,0,0,0,0,0,0,0,0
        ///Equipment,Amulet of avarice,Members,0.01,10,10,10,10,10,3,3,3, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,Notes
        ///Potions,Imp repellent,,0.1,Used in impling hunting and to make impling jars. Many types of flowers can be used to make it.
        ///Potions,Attack potion,,0.1,Temporarily raises Attack level by 10% + 3.
        ///Potions,Antipoison,,0.1,Cures poison and provides immunity for 90 seconds.
        ///Potions,Relicym&apos;s balm,,0.1,Cures disease and provides immunity for a short time.
        ///Potions,Strength potion,,0.1,Temporarily raises Strength level by 10% + 3.
        ///Potions,Serum 207,,0.1,Temporarily cures Afflicted [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Potions {
            get {
                return ResourceManager.GetString("Potions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,&apos;perfect&apos; ring,Members,0.007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,Archers ring,Members,0.004,0,0,0,0,4,0,0,0,0,4,0,0,0,0,0
        ///Equipment,Archers ring (i),Members,0.004,0,0,0,0,8,0,0,0,0,8,0,0,0,0,0
        ///Equipment,Beacon ring,Members,0.006,0,0,0,2,0,0,0,0,1,0,0,0,0,0,0
        ///Equipment,Berserker ring,Members,0.004,0,0,0,0,0,0,0,4,0,0,4,0,0,0,0
        ///Equipment, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth
        ///Runes,Air rune,Free-to-play,0
        ///Runes,Mind rune,Free-to-play,0
        ///Runes,Water rune,Free-to-play,0
        ///Runes,Earth rune,Free-to-play,0
        ///Runes,Fire rune,Free-to-play,0
        ///Runes,Body rune,Free-to-play,0
        ///Runes,Cosmic rune,Free-to-play,0
        ///Runes,Chaos rune,Free-to-play,0
        ///Runes,Nature rune,Free-to-play,0
        ///Runes,Law rune,Free-to-play,0
        ///Runes,Death rune,Free-to-play,0
        ///Runes,Astral rune,Members,0
        ///Runes,Blood rune,Members,0
        ///Runes,Soul rune,Members,0
        ///Runes,Wrath rune,Members,0
        ///Runes,Mist rune,M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Runes {
            get {
                return ResourceManager.GetString("Runes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed
        ///Equipment,3rd age kiteshield,Members,2.721,0,0,0,-10,-4,63,65,61,-3,63,0,0,0,0,0
        ///Equipment,A chair,Members,0.001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///Equipment,Adamant defender,Members,0.453,13,12,11,-3,-2,13,12,11,-3,-2,4,0,0,0,0
        ///Equipment,Adamant kiteshield,Free-to-play,5.896,0,0,0,-8,-2,27,31,29,-1,29,0,0,0,0,0
        ///Equipment,Adamant kiteshield (Arrav),Members [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,Name,Member,Weigth,StabAtk,SlashAtk,CrushAtk,MagicAtk,RangedAtk,StabDef,SlashDef,CrushDef,MagicDef,RangedDef,MeleStr,RangedStr,MagicStr,Prayer,Speed,WeaponType,IsTwoHanded
        ///Weapon,&apos;24-carat&apos; sword,Free-to-play,0.453,-100,-100,-50,0,0,0,0,0,0,0,-10,0,0,0,4,Stabbing swords,FALSE
        ///Weapon,3rd age axe,Members,1.36,-2,38,32,0,0,0,1,0,0,0,42,0,0,0,5,Axes,FALSE
        ///Weapon,3rd age bow,Members,3.175,0,0,0,0,80,0,0,0,0,0,0,0,0,0,4,Bows,TRUE
        ///Weapon,3rd age druidic staff,Members,2,7,-1,25,10,0,2,3,1,10,0,32,0,0,6,5,S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
    }
}
